load("input.mat")
load("realization.mat")
load("test_input.mat")
load("test_realization.mat")
subplot(2,2,1)
plot(input)
title("training input")
subplot(2,2,2)
plot(realization)
title("training output")
subplot(2,2,3)
plot(test_input)
title("test input")
subplot(2,2,4)
plot(test_realization)
title("test output")
soundsc(input, 48000)
soundsc(realization, 48000)
soundsc(test_input, 48000)
soundsc(test_realization, 48000)
wavwrite(input, 48000, "input.wav")
wavwrite(realization, 48000, "realization.wav")
wavwrite(test_input, 48000, "test_input.wav")
wavwrite(test_realization, 48000, "test_output.wav")
