load("corrupted.mat")
load("input.mat")
load("realization.mat")
load("test_input.mat")
load("test_realization.mat")
subplot(2,3,1)
plot(input)
subplot(2,3,2)
plot(corrupted)
title("corrupted/istorted training input")
subplot(2,3,3)
plot(realization)
title("training output")
subplot(2,3,4)
plot(test_input)
title("test input")
subplot(2,3,6)
plot(test_realization)
title("test output")
soundsc(input, 48000)
soundsc(realization, 48000)
soundsc(test_input, 48000)
soundsc(test_realization, 48000)
wavwrite(test_input, 48000, "test_input.wav")
wavwrite(test_realization, 48000, "test_output.wav")
